"""Regenerate `lintranslator/ocr_languages.py`: what tesseract can be told to read.

The Settings dialog offers the OCR languages as a list to tick, and that list has
to be the real one. `lintranslator/languages.py` cannot supply it: that table is
keyed by FLORES-200 code, so it names only the 100 traineddata files reachable
from a translation language and misses 24 that tesseract ships anyway
(`chi_sim_vert`, `deu_latf`, `enm`, `grc`, `lat`, ...). A chooser built from it
would quietly hide a fifth of the models.

Sources, both checkable:

  * the `tessdata_fast` file list at the revision `ocr.TESSDATA_REVISION` pins,
    which is the same revision every download is checksummed against
  * ISO 639-3 names from the system iso-codes data, which is where the model
    file names come from in the first place

Called with `--check` it verifies the generated file is current without writing,
which is what CI and `tests/test_ocr_languages.py` care about.

    .venv/bin/python probe/gen_ocr_languages.py            # needs network
    .venv/bin/python probe/gen_ocr_languages.py --check
"""
from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(APP_DIR))

from lintranslator.languages import LANGUAGES  # noqa: E402
from lintranslator.ocr import TESSDATA_REVISION  # noqa: E402

OUT = APP_DIR / "lintranslator" / "ocr_languages.py"
ISO_CODES_639_3 = Path("/usr/share/iso-codes/json/iso_639-3.json")

# Not language models: the script/orientation detector and the equation model.
NOT_LANGUAGES = {"osd", "equ"}

# tesseract's own suffixes on a file name, in the words the chooser should use.
# These are the 11 files whose name is a language plus a qualifier rather than a
# language; everything else is either an exact ISO 639-3 code or a FLORES name.
SUFFIX_NAMES = {
    "cyrl": "Cyrillic script",
    "latn": "Latin script",
    "latf": "Fraktur",
    "vert": "vertical",
    "old": "old",
}

# Names neither ISO nor the FLORES table can supply, because the file is neither
# a plain ISO code nor reachable from a translation language. Hand-written and
# deliberately short: the generator fails rather than guess, so every entry here
# is a decision someone made.
NAME_OVERRIDES = {
    "chi_sim": "Chinese (simplified)",
    "chi_tra": "Chinese (traditional)",
    # The vertical forms of the same two. `chi` is an ISO 639-2 code, not 639-3,
    # so the suffix rule cannot reach a base name for these.
    "chi_sim_vert": "Chinese (simplified), vertical",
    "chi_tra_vert": "Chinese (traditional), vertical",
}


def tessdata_stems() -> list[str]:
    """Every language model at the pinned revision, by the name `-l` takes."""
    url = (
        "https://api.github.com/repos/tesseract-ocr/tessdata_fast/contents/"
        f"?ref={TESSDATA_REVISION}"
    )
    request = urllib.request.Request(url, headers={"User-Agent": "lintranslator-probe"})
    entries = json.load(urllib.request.urlopen(request, timeout=60))
    return sorted(
        entry["name"][: -len(".traineddata")]
        for entry in entries
        if entry["name"].endswith(".traineddata")
        and entry["name"][: -len(".traineddata")] not in NOT_LANGUAGES
    )


def iso_names() -> dict[str, str]:
    data = json.loads(ISO_CODES_639_3.read_text(encoding="utf-8"))
    return {entry["alpha_3"]: entry["name"] for entry in data["639-3"]}


def flores_names() -> dict[str, str]:
    """traineddata stem -> the language a translation table reaches it from."""
    names: dict[str, str] = {}
    for language in LANGUAGES.values():
        if language.tesseract:
            names.setdefault(language.tesseract, language.name)
    return names


def name_for(stem: str, iso: dict[str, str], flores: dict[str, str]) -> tuple[str, str]:
    """The name to show, and which source it came from."""
    if stem in NAME_OVERRIDES:
        return NAME_OVERRIDES[stem], "override"
    if stem in iso:
        return iso[stem], "iso"
    base, _, suffix = stem.partition("_")
    if suffix and suffix in SUFFIX_NAMES and base in iso:
        return f"{iso[base]} ({SUFFIX_NAMES[suffix]})", "suffix"
    if stem in flores:
        return flores[stem], "flores"
    return "", "unnamed"


def render(rows: list[tuple[str, str]]) -> str:
    lines = [
        '"""Every OCR model `tessdata_fast` ships, for the Settings chooser.',
        "",
        "Generated by `probe/gen_ocr_languages.py` - see that file for the sources.",
        "Do not hand-edit; regenerate it and read the diff.",
        "",
        "`languages.py` cannot answer this: it is keyed by FLORES-200 code, so it",
        "names only the models reachable from a translation language and misses the",
        "rest of what `-l` accepts.",
        '"""',
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True)",
        "class OcrModel:",
        '    """One traineddata file: what `-l` takes, and what to call it."""',
        "",
        "    stem: str",
        "    name: str",
        "",
        "    @property",
        "    def label(self) -> str:",
        '        """How the chooser shows it: the name, then the stem it becomes."""',
        '        return f"{self.name} — {self.stem}"',
        "",
        "",
        "# stem -> name, sorted by stem. The order the chooser shows is `ordered()`,",
        "# which sorts by name instead, because that is what someone reads.",
        "_ROWS: dict[str, str] = {",
    ]
    for stem, name in rows:
        escaped = name.replace('"', '\\"')
        lines.append(f'    "{stem}": "{escaped}",')
    lines += [
        "}",
        "",
        "MODELS: tuple[OcrModel, ...] = tuple(",
        "    OcrModel(stem, name) for stem, name in sorted(_ROWS.items())",
        ")",
        "",
        "BY_STEM: dict[str, OcrModel] = {model.stem: model for model in MODELS}",
        "",
        "",
        "def get(stem: str | None) -> OcrModel | None:",
        '    """The model for an exact stem, or None when tesseract has no such file."""',
        "    return BY_STEM.get((stem or \"\").strip())",
        "",
        "",
        "def ordered() -> list[OcrModel]:",
        '    """The chooser\'s order: by the name a person reads, not by file name."""',
        "    return sorted(MODELS, key=lambda model: (model.name.casefold(), model.stem))",
        "",
        "",
        "def search(query: str) -> list[OcrModel]:",
        '    """Models matching `query` by name or stem, in chooser order."""',
        "    needle = query.strip().casefold()",
        "    if not needle:",
        "        return ordered()",
        "    return [",
        "        model",
        "        for model in ordered()",
        "        if needle in model.name.casefold() or needle in model.stem",
        "    ]",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    check = "--check" in argv
    iso, flores = iso_names(), flores_names()
    rows, sources, unnamed = [], {}, []
    for stem in tessdata_stems():
        name, source = name_for(stem, iso, flores)
        if not name:
            unnamed.append(stem)
            continue
        rows.append((stem, name))
        sources[source] = sources.get(source, 0) + 1

    if unnamed:
        print(
            "these models have no name from ISO 639-3 or the FLORES table; add "
            "them to NAME_OVERRIDES rather than letting a chooser show a bare "
            f"file name:\n  {' '.join(unnamed)}",
            file=sys.stderr,
        )
        return 1

    text = render(rows)
    if check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is out of date - regenerate it", file=sys.stderr)
            return 1
        print(f"{OUT.name} is current ({len(rows)} models)")
        return 0

    OUT.write_text(text, encoding="utf-8")
    by_source = ", ".join(f"{count} {name}" for name, count in sorted(sources.items()))
    print(f"wrote {OUT} - {len(rows)} models ({by_source})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
