"""The language table: what each backend is told, from one FLORES-200 code.

`translate.source_lang` and `translate.target_lang` are FLORES-200 codes
(`eng_Latn`, `jpn_Jpan`) because NLLB needs exactly those: the code is prepended
to the source tokens and used as the decoder prefix, and anything else is scored
as a language the model was never trained on. Every other backend wants something
different from the same language - a chat model wants the name "Japanese" in the
prompt, DeepL wants `JA`, Google wants `ja`, and tesseract needs `jpn.traineddata`
to read it in the first place - so this module is the single place those
translations live.

Getting one of them wrong is invisible: NLLB maps an unknown code to `<unk>` and
returns plausible-looking garbage with no error, and a chat prompt that says
"translate into jpn_Jpan" is merely ignored. That is why the Settings dialog
offers these codes from a list rather than as free text.

Generated by `probe/gen_languages.py` - see that file for the sources. Do not
hand-edit the table; regenerate it and read the diff.
"""
from __future__ import annotations

from dataclasses import dataclass

# FLORES script subtag -> the script is written without spaces between words, so
# token-level spacing in the output has to be normalised (see
# `translate.normalize_cjk`). `Hant`/`Hans` are the two Chinese scripts.
CJK_SCRIPTS = frozenset({"Jpan", "Hang", "Hans", "Hant"})

# Pinned to the top of the picker: the pairs this app was built and measured
# against, so the common case is one click rather than a search.
COMMON_CODES = (
    "eng_Latn",
    "jpn_Jpan",
    "kor_Hang",
    "zho_Hans",
    "zho_Hant",
    "deu_Latn",
    "fra_Latn",
    "spa_Latn",
    "rus_Cyrl",
    "por_Latn",
    "ita_Latn",
    "ukr_Cyrl",
    "vie_Latn",
    "tha_Thai",
    "ind_Latn",
    "tur_Latn",
    "pol_Latn",
    "nld_Latn",
    "arb_Arab",
    "hin_Deva",
)


@dataclass(frozen=True)
class Language:
    """One FLORES-200 language, with the code each backend needs for it."""

    code: str
    name: str
    # ISO 639-1, which is what Google's endpoint takes. None where no 639-1 code
    # exists (most of the 202 have none).
    iso: str | None = None
    # DeepL's own code, or None where DeepL cannot translate this language.
    deepl: str | None = None
    # tessdata_fast file stem for OCR, or None where tesseract has no model.
    tesseract: str | None = None

    @property
    def script(self) -> str:
        """The FLORES script subtag, e.g. "Jpan"."""
        return self.code.split("_", 1)[1]

    @property
    def cjk(self) -> bool:
        return self.script in CJK_SCRIPTS

    @property
    def short(self) -> str:
        """The bare language part, e.g. "jpn" - for tight labels."""
        return self.code.split("_", 1)[0]

    @property
    def label(self) -> str:
        """How the picker shows it: the name a person reads, then the code."""
        return f"{self.name} — {self.code}"


# code -> (name, iso, deepl, tesseract)
_ROWS: dict[str, tuple] = {
    "ace_Arab": ("Acehnese (Arabic script)", None, None, None),
    "ace_Latn": ("Acehnese (Latin script)", None, None, None),
    "acm_Arab": ("Mesopotamian Arabic", "ar", "AR", None),
    "acq_Arab": ("Ta’izzi-Adeni Arabic", "ar", "AR", None),
    "aeb_Arab": ("Tunisian Arabic", "ar", "AR", None),
    "afr_Latn": ("Afrikaans", "af", None, "afr"),
    "ajp_Arab": ("South Levantine Arabic", "ar", "AR", None),
    "aka_Latn": ("Akan", "ak", None, None),
    "als_Latn": ("Tosk Albanian", "sq", None, "sqi"),
    "amh_Ethi": ("Amharic", "am", None, "amh"),
    "apc_Arab": ("North Levantine Arabic", "ar", "AR", None),
    "arb_Arab": ("Modern Standard Arabic", "ar", "AR", "ara"),
    "ars_Arab": ("Najdi Arabic", "ar", "AR", None),
    "ary_Arab": ("Moroccan Arabic", "ar", "AR", None),
    "arz_Arab": ("Egyptian Arabic", "ar", "AR", None),
    "asm_Beng": ("Assamese", "as", None, "asm"),
    "ast_Latn": ("Asturian", None, None, None),
    "awa_Deva": ("Awadhi", "hi", None, None),
    "ayr_Latn": ("Central Aymara", "ay", None, None),
    "azb_Arab": ("South Azerbaijani", "az", None, None),
    "azj_Latn": ("North Azerbaijani", "az", None, "aze"),
    "bak_Cyrl": ("Bashkir", "ba", None, None),
    "bam_Latn": ("Bambara", "bm", None, None),
    "ban_Latn": ("Balinese", None, None, None),
    "bel_Cyrl": ("Belarusian", "be", None, "bel"),
    "bem_Latn": ("Bemba", None, None, None),
    "ben_Beng": ("Bengali", "bn", None, "ben"),
    "bho_Deva": ("Bhojpuri", "hi", None, None),
    "bjn_Arab": ("Banjar (Arabic script)", None, None, None),
    "bjn_Latn": ("Banjar (Latin script)", None, None, None),
    "bod_Tibt": ("Standard Tibetan", "bo", None, "bod"),
    "bos_Latn": ("Bosnian", "bs", None, "bos"),
    "bug_Latn": ("Buginese", None, None, None),
    "bul_Cyrl": ("Bulgarian", "bg", "BG", "bul"),
    "cat_Latn": ("Catalan", "ca", None, "cat"),
    "ceb_Latn": ("Cebuano", None, None, "ceb"),
    "ces_Latn": ("Czech", "cs", "CS", "ces"),
    "cjk_Latn": ("Chokwe", None, None, None),
    "ckb_Arab": ("Central Kurdish", "ku", None, None),
    "crh_Latn": ("Crimean Tatar", None, None, None),
    "cym_Latn": ("Welsh", "cy", None, "cym"),
    "dan_Latn": ("Danish", "da", "DA", "dan"),
    "deu_Latn": ("German", "de", "DE", "deu"),
    "dik_Latn": ("Southwestern Dinka", None, None, None),
    "dyu_Latn": ("Dyula", None, None, None),
    "dzo_Tibt": ("Dzongkha", "dz", None, "dzo"),
    "ell_Grek": ("Greek", "el", "EL", "ell"),
    "eng_Latn": ("English", "en", "EN", "eng"),
    "epo_Latn": ("Esperanto", "eo", None, "epo"),
    "est_Latn": ("Estonian", "et", "ET", "est"),
    "eus_Latn": ("Basque", "eu", None, "eus"),
    "ewe_Latn": ("Ewe", "ee", None, None),
    "fao_Latn": ("Faroese", "fo", None, "fao"),
    "fij_Latn": ("Fijian", "fj", None, None),
    "fin_Latn": ("Finnish", "fi", "FI", "fin"),
    "fon_Latn": ("Fon", None, None, None),
    "fra_Latn": ("French", "fr", "FR", "fra"),
    "fur_Latn": ("Friulian", None, None, None),
    "fuv_Latn": ("Nigerian Fulfulde", "ff", None, None),
    "gaz_Latn": ("West Central Oromo", "om", None, None),
    "gla_Latn": ("Scottish Gaelic", "gd", None, "gla"),
    "gle_Latn": ("Irish", "ga", None, "gle"),
    "glg_Latn": ("Galician", "gl", None, "glg"),
    "grn_Latn": ("Guarani", "gn", None, None),
    "guj_Gujr": ("Gujarati", "gu", None, "guj"),
    "hat_Latn": ("Haitian Creole", "ht", None, "hat"),
    "hau_Latn": ("Hausa", "ha", None, None),
    "heb_Hebr": ("Hebrew", "he", "HE", "heb"),
    "hin_Deva": ("Hindi", "hi", None, "hin"),
    "hne_Deva": ("Chhattisgarhi", "hi", None, None),
    "hrv_Latn": ("Croatian", "hr", None, "hrv"),
    "hun_Latn": ("Hungarian", "hu", "HU", "hun"),
    "hye_Armn": ("Armenian", "hy", None, "hye"),
    "ibo_Latn": ("Igbo", "ig", None, None),
    "ilo_Latn": ("Ilocano", None, None, None),
    "ind_Latn": ("Indonesian", "id", "ID", "ind"),
    "isl_Latn": ("Icelandic", "is", None, "isl"),
    "ita_Latn": ("Italian", "it", "IT", "ita"),
    "jav_Latn": ("Javanese", "jv", None, "jav"),
    "jpn_Jpan": ("Japanese", "ja", "JA", "jpn"),
    "kab_Latn": ("Kabyle", None, None, None),
    "kac_Latn": ("Jingpho", None, None, None),
    "kam_Latn": ("Kamba", None, None, None),
    "kan_Knda": ("Kannada", "kn", None, "kan"),
    "kas_Arab": ("Kashmiri (Arabic script)", "ks", None, None),
    "kas_Deva": ("Kashmiri (Devanagari script)", "ks", None, None),
    "kat_Geor": ("Georgian", "ka", None, "kat"),
    "kaz_Cyrl": ("Kazakh", "kk", None, "kaz"),
    "kbp_Latn": ("Kabiyè", None, None, None),
    "kea_Latn": ("Kabuverdianu", None, None, None),
    "khk_Cyrl": ("Halh Mongolian", "mn", None, "mon"),
    "khm_Khmr": ("Khmer", "km", None, "khm"),
    "kik_Latn": ("Kikuyu", "ki", None, None),
    "kin_Latn": ("Kinyarwanda", "rw", None, None),
    "kir_Cyrl": ("Kyrgyz", "ky", None, "kir"),
    "kmb_Latn": ("Kimbundu", None, None, None),
    "kmr_Latn": ("Northern Kurdish", "ku", None, "kmr"),
    "knc_Arab": ("Central Kanuri (Arabic script)", "kr", None, None),
    "knc_Latn": ("Central Kanuri (Latin script)", "kr", None, None),
    "kon_Latn": ("Kikongo", "kg", None, None),
    "kor_Hang": ("Korean", "ko", "KO", "kor"),
    "lao_Laoo": ("Lao", "lo", None, "lao"),
    "lij_Latn": ("Ligurian", None, None, None),
    "lim_Latn": ("Limburgish", "li", None, None),
    "lin_Latn": ("Lingala", "ln", None, None),
    "lit_Latn": ("Lithuanian", "lt", "LT", "lit"),
    "lmo_Latn": ("Lombard", None, None, None),
    "ltg_Latn": ("Latgalian", None, None, None),
    "ltz_Latn": ("Luxembourgish", "lb", None, "ltz"),
    "lua_Latn": ("Luba-Kasai", None, None, None),
    "lug_Latn": ("Ganda", "lg", None, None),
    "luo_Latn": ("Luo", None, None, None),
    "lus_Latn": ("Mizo", None, None, None),
    "lvs_Latn": ("Standard Latvian", "lv", "LV", "lav"),
    "mag_Deva": ("Magahi", "hi", None, None),
    "mai_Deva": ("Maithili", "hi", None, None),
    "mal_Mlym": ("Malayalam", "ml", None, "mal"),
    "mar_Deva": ("Marathi", "mr", None, "mar"),
    "min_Latn": ("Minangkabau (Latin script)", None, None, None),
    "mkd_Cyrl": ("Macedonian", "mk", None, "mkd"),
    "mlt_Latn": ("Maltese", "mt", None, "mlt"),
    "mni_Beng": ("Meitei (Bengali script)", None, None, None),
    "mos_Latn": ("Mossi", None, None, None),
    "mri_Latn": ("Maori", "mi", None, "mri"),
    "mya_Mymr": ("Burmese", "my", None, "mya"),
    "nld_Latn": ("Dutch", "nl", "NL", "nld"),
    "nno_Latn": ("Norwegian Nynorsk", "nn", None, "nor"),
    "nob_Latn": ("Norwegian Bokmål", "nb", "NB", "nor"),
    "npi_Deva": ("Nepali", "ne", None, "nep"),
    "nso_Latn": ("Northern Sotho", None, None, None),
    "nus_Latn": ("Nuer", None, None, None),
    "nya_Latn": ("Nyanja", "ny", None, None),
    "oci_Latn": ("Occitan", "oc", None, "oci"),
    "ory_Orya": ("Odia", "or", None, "ori"),
    "pag_Latn": ("Pangasinan", None, None, None),
    "pan_Guru": ("Eastern Panjabi", "pa", None, "pan"),
    "pap_Latn": ("Papiamento", None, None, None),
    "pbt_Arab": ("Southern Pashto", "ps", None, "pus"),
    "pes_Arab": ("Western Persian", "fa", None, "fas"),
    "plt_Latn": ("Plateau Malagasy", "mg", None, None),
    "pol_Latn": ("Polish", "pl", "PL", "pol"),
    "por_Latn": ("Portuguese", "pt", "PT", "por"),
    "prs_Arab": ("Dari", "fa", None, "fas"),
    "quy_Latn": ("Ayacucho Quechua", "qu", None, "que"),
    "ron_Latn": ("Romanian", "ro", "RO", "ron"),
    "run_Latn": ("Rundi", "rn", None, None),
    "rus_Cyrl": ("Russian", "ru", "RU", "rus"),
    "sag_Latn": ("Sango", "sg", None, None),
    "san_Deva": ("Sanskrit", "sa", None, "san"),
    "sat_Beng": ("Santali (Bengali script)", None, None, None),
    "scn_Latn": ("Sicilian", None, None, None),
    "shn_Mymr": ("Shan", None, None, None),
    "sin_Sinh": ("Sinhala", "si", None, "sin"),
    "slk_Latn": ("Slovak", "sk", "SK", "slk"),
    "slv_Latn": ("Slovenian", "sl", "SL", "slv"),
    "smo_Latn": ("Samoan", "sm", None, None),
    "sna_Latn": ("Shona", "sn", None, None),
    "snd_Arab": ("Sindhi", "sd", None, "snd"),
    "som_Latn": ("Somali", "so", None, None),
    "sot_Latn": ("Southern Sotho", "st", None, None),
    "spa_Latn": ("Spanish", "es", "ES", "spa"),
    "srd_Latn": ("Sardinian", "sc", None, None),
    "srp_Cyrl": ("Serbian", "sr", None, "srp"),
    "ssw_Latn": ("Swati", "ss", None, None),
    "sun_Latn": ("Sundanese", "su", None, "sun"),
    "swe_Latn": ("Swedish", "sv", "SV", "swe"),
    "swh_Latn": ("Swahili", "sw", None, "swa"),
    "szl_Latn": ("Silesian", None, None, None),
    "tam_Taml": ("Tamil", "ta", None, "tam"),
    "taq_Latn": ("Tamasheq (Latin script)", None, None, None),
    "taq_Tfng": ("Tamasheq (Tifinagh script)", None, None, None),
    "tat_Cyrl": ("Tatar", "tt", None, "tat"),
    "tel_Telu": ("Telugu", "te", None, "tel"),
    "tgk_Cyrl": ("Tajik", "tg", None, "tgk"),
    "tgl_Latn": ("Tagalog", "tl", None, "fil"),
    "tha_Thai": ("Thai", "th", "TH", "tha"),
    "tir_Ethi": ("Tigrinya", "ti", None, "tir"),
    "tpi_Latn": ("Tok Pisin", None, None, None),
    "tsn_Latn": ("Tswana", "tn", None, None),
    "tso_Latn": ("Tsonga", "ts", None, None),
    "tuk_Latn": ("Turkmen", "tk", None, None),
    "tum_Latn": ("Tumbuka", None, None, None),
    "tur_Latn": ("Turkish", "tr", "TR", "tur"),
    "twi_Latn": ("Twi", "tw", None, None),
    "tzm_Tfng": ("Central Atlas Tamazight", None, None, None),
    "uig_Arab": ("Uyghur", "ug", None, "uig"),
    "ukr_Cyrl": ("Ukrainian", "uk", "UK", "ukr"),
    "umb_Latn": ("Umbundu", None, None, None),
    "urd_Arab": ("Urdu", "ur", None, "urd"),
    "uzn_Latn": ("Northern Uzbek", "uz", None, "uzb"),
    "vec_Latn": ("Venetian", None, None, None),
    "vie_Latn": ("Vietnamese", "vi", "VI", "vie"),
    "war_Latn": ("Waray", None, None, None),
    "wol_Latn": ("Wolof", "wo", None, None),
    "xho_Latn": ("Xhosa", "xh", None, None),
    "ydd_Hebr": ("Eastern Yiddish", None, None, "yid"),
    "yor_Latn": ("Yoruba", "yo", None, "yor"),
    "yue_Hant": ("Yue Chinese", None, None, None),
    "zho_Hans": ("Chinese (Simplified)", "zh", "ZH", "chi_sim"),
    "zho_Hant": ("Chinese (Traditional)", "zh", "ZH", "chi_tra"),
    "zsm_Latn": ("Standard Malay", "ms", None, "msa"),
    "zul_Latn": ("Zulu", "zu", None, None),
}

LANGUAGES: dict[str, Language] = {
    code: Language(code, *row) for code, row in _ROWS.items()
}

# Every code NLLB accepts, as a set: the picker's vocabulary and the thing a
# config value is validated against.
CODES: frozenset[str] = frozenset(LANGUAGES)


def get(code: str | None) -> Language | None:
    """The language for an exact FLORES-200 code, or None if it is not one."""
    if not code:
        return None
    return LANGUAGES.get(code.strip())


def _by_base(base: str) -> Language | None:
    """The first language whose language part is `base`, e.g. "jpn" -> jpn_Jpan.

    Script variants share a language part (`zho_Hans`, `zho_Hant`), so this is
    ambiguous by nature and only used where the script cannot matter.
    """
    if not base:
        return None
    for language in LANGUAGES.values():
        if language.short == base:
            return language
    return None


def language_name(code: str) -> str:
    """A readable name for a code, whether or not the code is valid.

    Config files are edited by hand, and an older version of this app may have
    written a bare ISO code into one, so a prompt can be asked to translate
    "into jpn". Anything unrecognised is passed through unchanged rather than
    replaced by a guess: "translate into jpn" is still a translation request,
    whereas silently rewriting an unknown target to English translates into the
    wrong language.
    """
    language = get(code)
    if language is not None:
        return language.name
    stripped = (code or "").strip()
    by_base = _by_base(stripped.split("_")[0])
    return by_base.name if by_base is not None else stripped


def iso_code(code: str) -> str | None:
    """ISO 639-1 for a code, or None when it has none.

    None is a real answer, not a failure: most of the 202 languages have no
    639-1 code, and an API that only takes 639-1 codes has to be told so.
    """
    language = get(code)
    return language.iso if language is not None else None


def short_code(code: str) -> str:
    """The bare language part, for a label: "eng_Latn" -> "eng".

    Unknown values are passed through, so the panel shows whatever the config
    actually holds rather than a tidied-up version of it.
    """
    language = get(code)
    return language.short if language is not None else (code or "").strip()


def deepl_code(code: str) -> str | None:
    """DeepL's code for a language, or None where DeepL cannot do it."""
    language = get(code)
    return language.deepl if language is not None else None


def tesseract_lang(code: str) -> str | None:
    """The tessdata file stem to read this language with, or None.

    None means tesseract has no model for it, which is worth saying out loud:
    the OCR would otherwise keep running with whatever language it was given
    and quietly return nonsense for every line.
    """
    language = get(code)
    return language.tesseract if language is not None else None


def is_cjk(code: str) -> bool:
    """Whether the language is written without spaces between words."""
    language = get(code)
    return bool(language and language.cjk)


def ordered() -> list[Language]:
    """COMMON_CODES first, then everything else by name.

    The picker's order. The common languages are the ones this app was built
    against, and a filtered list that buries Japanese under "Acehnese" is a
    worse list even though both are one search away.
    """
    common = [LANGUAGES[code] for code in COMMON_CODES if code in LANGUAGES]
    pinned = set(COMMON_CODES)
    rest = sorted(
        (lang for code, lang in LANGUAGES.items() if code not in pinned),
        key=lambda lang: (lang.name, lang.code),
    )
    return common + rest


def search(query: str) -> list[Language]:
    """Filter by name or code. Empty query returns `ordered()`."""
    needle = (query or "").strip().lower()
    if not needle:
        return ordered()
    return [
        language
        for language in ordered()
        if needle in language.name.lower() or needle in language.code.lower()
    ]
