"""Every OCR model `tessdata_fast` ships, for the Settings chooser.

Generated by `probe/gen_ocr_languages.py` - see that file for the sources.
Do not hand-edit; regenerate it and read the diff.

`languages.py` cannot answer this: it is keyed by FLORES-200 code, so it
names only the models reachable from a translation language and misses the
rest of what `-l` accepts.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class OcrModel:
    """One traineddata file: what `-l` takes, and what to call it."""

    stem: str
    name: str

    @property
    def label(self) -> str:
        """How the chooser shows it: the name, then the stem it becomes."""
        return f"{self.name} — {self.stem}"


# stem -> name, sorted by stem. The order the chooser shows is `ordered()`,
# which sorts by name instead, because that is what someone reads.
_ROWS: dict[str, str] = {
    "afr": "Afrikaans",
    "amh": "Amharic",
    "ara": "Arabic",
    "asm": "Assamese",
    "aze": "Azerbaijani",
    "aze_cyrl": "Azerbaijani (Cyrillic script)",
    "bel": "Belarusian",
    "ben": "Bengali",
    "bod": "Tibetan",
    "bos": "Bosnian",
    "bre": "Breton",
    "bul": "Bulgarian",
    "cat": "Catalan",
    "ceb": "Cebuano",
    "ces": "Czech",
    "chi_sim": "Chinese (simplified)",
    "chi_sim_vert": "Chinese (simplified), vertical",
    "chi_tra": "Chinese (traditional)",
    "chi_tra_vert": "Chinese (traditional), vertical",
    "chr": "Cherokee",
    "cos": "Corsican",
    "cym": "Welsh",
    "dan": "Danish",
    "deu": "German",
    "deu_latf": "German (Fraktur)",
    "div": "Divehi",
    "dzo": "Dzongkha",
    "ell": "Modern Greek (1453-)",
    "eng": "English",
    "enm": "Middle English (1100-1500)",
    "epo": "Esperanto",
    "est": "Estonian",
    "eus": "Basque",
    "fao": "Faroese",
    "fas": "Persian",
    "fil": "Filipino",
    "fin": "Finnish",
    "fra": "French",
    "frk": "Frankish",
    "frm": "Middle French (ca. 1400-1600)",
    "fry": "Western Frisian",
    "gla": "Scottish Gaelic",
    "gle": "Irish",
    "glg": "Galician",
    "grc": "Ancient Greek (to 1453)",
    "guj": "Gujarati",
    "hat": "Haitian",
    "heb": "Hebrew",
    "hin": "Hindi",
    "hrv": "Croatian",
    "hun": "Hungarian",
    "hye": "Armenian",
    "iku": "Inuktitut",
    "ind": "Indonesian",
    "isl": "Icelandic",
    "ita": "Italian",
    "ita_old": "Italian (old)",
    "jav": "Javanese",
    "jpn": "Japanese",
    "jpn_vert": "Japanese (vertical)",
    "kan": "Kannada",
    "kat": "Georgian",
    "kat_old": "Georgian (old)",
    "kaz": "Kazakh",
    "khm": "Khmer",
    "kir": "Kirghiz",
    "kmr": "Northern Kurdish",
    "kor": "Korean",
    "kor_vert": "Korean (vertical)",
    "lao": "Lao",
    "lat": "Latin",
    "lav": "Latvian",
    "lit": "Lithuanian",
    "ltz": "Luxembourgish",
    "mal": "Malayalam",
    "mar": "Marathi",
    "mkd": "Macedonian",
    "mlt": "Maltese",
    "mon": "Mongolian",
    "mri": "Maori",
    "msa": "Malay (macrolanguage)",
    "mya": "Burmese",
    "nep": "Nepali (macrolanguage)",
    "nld": "Dutch",
    "nor": "Norwegian",
    "oci": "Occitan (post 1500)",
    "ori": "Oriya (macrolanguage)",
    "pan": "Panjabi",
    "pol": "Polish",
    "por": "Portuguese",
    "pus": "Pushto",
    "que": "Quechua",
    "ron": "Romanian",
    "rus": "Russian",
    "san": "Sanskrit",
    "sin": "Sinhala",
    "slk": "Slovak",
    "slv": "Slovenian",
    "snd": "Sindhi",
    "spa": "Spanish",
    "spa_old": "Spanish (old)",
    "sqi": "Albanian",
    "srp": "Serbian",
    "srp_latn": "Serbian (Latin script)",
    "sun": "Sundanese",
    "swa": "Swahili (macrolanguage)",
    "swe": "Swedish",
    "syr": "Syriac",
    "tam": "Tamil",
    "tat": "Tatar",
    "tel": "Telugu",
    "tgk": "Tajik",
    "tha": "Thai",
    "tir": "Tigrinya",
    "ton": "Tonga (Tonga Islands)",
    "tur": "Turkish",
    "uig": "Uighur",
    "ukr": "Ukrainian",
    "urd": "Urdu",
    "uzb": "Uzbek",
    "uzb_cyrl": "Uzbek (Cyrillic script)",
    "vie": "Vietnamese",
    "yid": "Yiddish",
    "yor": "Yoruba",
}

MODELS: tuple[OcrModel, ...] = tuple(
    OcrModel(stem, name) for stem, name in sorted(_ROWS.items())
)

BY_STEM: dict[str, OcrModel] = {model.stem: model for model in MODELS}


def get(stem: str | None) -> OcrModel | None:
    """The model for an exact stem, or None when tesseract has no such file."""
    return BY_STEM.get((stem or "").strip())


def ordered() -> list[OcrModel]:
    """The chooser's order: by the name a person reads, not by file name."""
    return sorted(MODELS, key=lambda model: (model.name.casefold(), model.stem))


def search(query: str) -> list[OcrModel]:
    """Models matching `query` by name or stem, in chooser order."""
    needle = query.strip().casefold()
    if not needle:
        return ordered()
    return [
        model
        for model in ordered()
        if needle in model.name.casefold() or needle in model.stem
    ]
